/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeRouteImport } from './routes/me'
import { Route as PayRouteImport } from './routes/pay'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AddressesIndexRouteImport } from './routes/addresses/index'
import { Route as AddressesNewRouteImport } from './routes/addresses/new'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as OrdersIdRouteImport } from './routes/orders/$id'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as AddressesIdEditRouteImport } from './routes/addresses/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesIndexRoute = AddressesIndexRouteImport.update({
  id: '/addresses/',
  path: '/addresses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesNewRoute = AddressesNewRouteImport.update({
  id: '/addresses/new',
  path: '/addresses/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesIdEditRoute = AddressesIdEditRouteImport.update({
  id: '/addresses/$id/edit',
  path: '/addresses/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/pay': typeof PayRoute
  '/register': typeof RegisterRoute
  '/addresses/new': typeof AddressesNewRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/addresses/': typeof AddressesIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/addresses/$id/edit': typeof AddressesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/pay': typeof PayRoute
  '/register': typeof RegisterRoute
  '/addresses/new': typeof AddressesNewRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/addresses': typeof AddressesIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/addresses/$id/edit': typeof AddressesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/pay': typeof PayRoute
  '/register': typeof RegisterRoute
  '/addresses/new': typeof AddressesNewRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/addresses/': typeof AddressesIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/addresses/$id/edit': typeof AddressesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/me'
    | '/pay'
    | '/register'
    | '/addresses/new'
    | '/orders/$id'
    | '/products/$id'
    | '/addresses/'
    | '/orders/'
    | '/addresses/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/me'
    | '/pay'
    | '/register'
    | '/addresses/new'
    | '/orders/$id'
    | '/products/$id'
    | '/addresses'
    | '/orders'
    | '/addresses/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/me'
    | '/pay'
    | '/register'
    | '/addresses/new'
    | '/orders/$id'
    | '/products/$id'
    | '/addresses/'
    | '/orders/'
    | '/addresses/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  PayRoute: typeof PayRoute
  RegisterRoute: typeof RegisterRoute
  AddressesNewRoute: typeof AddressesNewRoute
  OrdersIdRoute: typeof OrdersIdRoute
  ProductsIdRoute: typeof ProductsIdRoute
  AddressesIndexRoute: typeof AddressesIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  AddressesIdEditRoute: typeof AddressesIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses/': {
      id: '/addresses/'
      path: '/addresses'
      fullPath: '/addresses/'
      preLoaderRoute: typeof AddressesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses/new': {
      id: '/addresses/new'
      path: '/addresses/new'
      fullPath: '/addresses/new'
      preLoaderRoute: typeof AddressesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses/$id/edit': {
      id: '/addresses/$id/edit'
      path: '/addresses/$id/edit'
      fullPath: '/addresses/$id/edit'
      preLoaderRoute: typeof AddressesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  PayRoute: PayRoute,
  RegisterRoute: RegisterRoute,
  AddressesNewRoute: AddressesNewRoute,
  OrdersIdRoute: OrdersIdRoute,
  ProductsIdRoute: ProductsIdRoute,
  AddressesIndexRoute: AddressesIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  AddressesIdEditRoute: AddressesIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
