export {
  createCategory,
  createProduct,
  getProductById,
  getProductByIdPublic,
  getSkuPurchaseInfo,
  getSkusByIds,
  getSkuViewsByIds,
  listAllProducts,
  listCategories,
  listLowStockSkus,
  listPublishedProducts,
  reduceProductStock,
  removeCategory,
  removeProduct,
  restoreProductStock,
  type SkuView,
  updateCategory,
  updateProduct,
} from './service'
